"use client";

import { Navbar } from "@/components/landing/Navbar";
import { Footer } from "@/components/landing/Footer";
import {
  Server,
  Database,
  Key,
  Layers,
  Shield,
  Gauge,
  Folder,
} from "@/components/animated-icons";
import { Reveal } from "@/components/landing/motion";
import {
  Container,
  LandingShell,
  PageHero,
  Section,
  SectionHeader,
} from "@/components/landing/layout";

const tiers = [
  {
    layer: "Presentation",
    tech: "Next.js 16 · Electron · Expo",
    icon: Layers,
    description:
      "One client ecosystem across web, desktop and mobile, sharing TypeScript types, design tokens and components.",
    points: [
      "Next.js 16 App Router, Tailwind CSS v4",
      "Windows Electron app with global hotkey capture (Ctrl+Shift+F)",
      "Android React Native companion with push notifications",
      "Shared motion language and theme tokens across surfaces",
    ],
  },
  {
    layer: "Backend",
    tech: "Python FastAPI (async)",
    icon: Server,
    description:
      "High-throughput asynchronous REST core with typed Pydantic V2 models and live OpenAPI documentation.",
    points: [
      "Sub-20ms async request handlers",
      "SQLAlchemy 2.0 async engine with connection pooling",
      "Auto-generated OpenAPI 3.1 spec at /docs",
      "AI orchestration for Gemini & OpenAI models",
    ],
  },
  {
    layer: "Database",
    tech: "Neon PostgreSQL (serverless)",
    icon: Database,
    description:
      "Serverless Postgres with autoscaling, automated backups and branch-based workflows — zero maintenance overhead.",
    points: [
      "Generous free tier keeps the core plan free",
      "Schema-managed through versioned SQL migrations",
      "Workspace-scoped tables for clients, projects, invoices",
      "Scale-to-zero between traffic peaks",
    ],
  },
  {
    layer: "Identity",
    tech: "Clerk JWT · RBAC",
    icon: Key,
    description:
      "Authentication with social OAuth, MFA and session revocation — passwords never touch our servers.",
    points: [
      "Bearer JWT verified in FastAPI middleware against Clerk JWKS",
      "Role-based access within each workspace",
      "Workspace-scoped isolation for every query",
      "Seamless session refresh across web, desktop and mobile",
    ],
  },
  {
    layer: "Storage",
    tech: "Cloudinary object storage",
    icon: Shield,
    description:
      "Contract PDFs, receipts and client deliverables served from a global CDN with signed uploads.",
    points: [
      "Signed URL uploads generated by FastAPI",
      "Automated PDF invoice rendering straight to storage",
      "Access-logged, per-client share tokens",
      "Encrypted at rest",
    ],
  },
  {
    layer: "Hardening",
    tech: "Middleware & rate limits",
    icon: Gauge,
    description:
      "A hardened request pipeline in front of every endpoint.",
    points: [
      "Per-IP sliding-window rate limits on public endpoints",
      "Strict CORS allow-list and sanitized error responses",
      "Security headers on every response (HSTS, nosniff, DENY)",
      "Tokenized, revocable share links",
    ],
  },
];

const monorepo = [
  { path: "apps/web", desc: "Next.js 16 App Router · Tailwind CSS v4 · shadcn/ui" },
  { path: "apps/api", desc: "FastAPI · Python 3.12 · SQLAlchemy 2.0 · Neon Postgres" },
  { path: "apps/desktop", desc: "Electron shell · global quick capture" },
  { path: "apps/mobile", desc: "React Native · Expo · push + offline sync" },
  { path: "packages/types", desc: "Shared TypeScript contracts for every client" },
];

export default function ArchitecturePage() {
  return (
    <LandingShell>
      <Navbar />

      <main className="flex-1">
        <PageHero
          eyebrow="Architecture"
          title="Free-first,"
          accent="serverless by design."
          desc="Built so the running cost of your workspace stays near zero — Neon Postgres that scales to idle, an async Python core, and no servers to babysit."
        />

        {/* Layer spec sheet — rows, not a card grid */}
        <Section className="border-t-0">
          <Container>
            <div className="border-t border-line">
              {tiers.map((tier, idx) => {
                const Icon = tier.icon;
                return (
                  <Reveal key={tier.layer} delay={idx * 0.04}>
                    <div className="grid sm:grid-cols-[240px_1fr] gap-3 sm:gap-10 py-8 border-b border-line">
                      <div className="flex items-start gap-3">
                        <span className="w-8 h-8 rounded-lg bg-accent-soft dark:bg-accent/15 text-accent flex items-center justify-center shrink-0 mt-0.5">
                          <Icon className="w-4 h-4" />
                        </span>
                        <div>
                          <div className="eyebrow !text-[10px] mb-1.5">
                            {String(idx + 1).padStart(2, "0")} · {tier.layer}
                          </div>
                          <h2 className="font-display text-[16px] font-semibold text-fg leading-snug">
                            {tier.tech}
                          </h2>
                        </div>
                      </div>
                      <div>
                        <p className="text-[14px] leading-7 text-muted mb-4">{tier.description}</p>
                        <div className="grid sm:grid-cols-2 gap-x-8 gap-y-2">
                          {tier.points.map((p) => (
                            <div key={p} className="flex items-start gap-2.5 text-[13px] leading-5 text-fg/90">
                              <span className="w-1 h-1 rounded-full bg-line-strong shrink-0 mt-2" />
                              <span>{p}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  </Reveal>
                );
              })}
            </div>
          </Container>
        </Section>

        {/* Monorepo topology — one quiet terminal-styled block */}
        <Section>
          <Container>
            <SectionHeader
              eyebrow="Monorepo"
              title="One repository,"
              accent="four clients, shared contracts."
              desc="Web, API, desktop and mobile live together with a shared types package, so every client speaks the same schema."
            />
            <Reveal>
              <div className="max-w-3xl mx-auto rounded-xl border border-line bg-card overflow-hidden">
                <div className="flex items-center gap-2.5 px-4 py-2.5 border-b border-line bg-surface/60">
                  <Folder className="w-3.5 h-3.5 text-muted" />
                  <span className="font-mono text-[10px] text-faint tracking-wider">freelance-book/</span>
                </div>
                <div className="p-4 sm:p-5 font-mono text-[12px] leading-6">
                  {monorepo.map((m) => (
                    <div
                      key={m.path}
                      className="flex flex-col sm:flex-row sm:items-baseline gap-0.5 sm:gap-4 py-2 border-b border-line last:border-b-0"
                    >
                      <span className="text-accent shrink-0">{m.path}</span>
                      <span className="text-muted">{m.desc}</span>
                    </div>
                  ))}
                </div>
              </div>
            </Reveal>
          </Container>
        </Section>
      </main>

      <Footer />
    </LandingShell>
  );
}
