"use client";

import { Navbar } from "@/components/landing/Navbar";
import { Footer } from "@/components/landing/Footer";
import { Rise } from "@/components/landing/motion";
import {
  Container,
  LandingShell,
  PageHero,
  Section,
  WindowFrame,
} from "@/components/landing/layout";

/* ------------------------------------------------------------------
   Architecture — spec-sheet rows for the six layers plus a terminal
   window for the monorepo topology.
------------------------------------------------------------------- */

const tiers = [
  {
    layer: "Presentation",
    tech: "Next.js 16 · Electron · Expo",
    description:
      "One client ecosystem across web, desktop and mobile, sharing TypeScript types, design tokens and components.",
    points: [
      "Next.js 16 App Router, Tailwind CSS v4",
      "Windows Electron app with global hotkey capture (Ctrl+Shift+F)",
      "Android React Native companion with push notifications",
      "Shared motion language and theme tokens across surfaces",
    ],
  },
  {
    layer: "Backend",
    tech: "Python FastAPI (async)",
    description:
      "High-throughput asynchronous REST core with typed Pydantic V2 models and live OpenAPI documentation.",
    points: [
      "Sub-20ms async request handlers",
      "SQLAlchemy 2.0 async engine with connection pooling",
      "Auto-generated OpenAPI 3.1 spec at /docs",
      "AI orchestration for Gemini & OpenAI models",
    ],
  },
  {
    layer: "Database",
    tech: "Neon PostgreSQL (serverless)",
    description:
      "Serverless Postgres with autoscaling, automated backups and branch-based workflows — zero maintenance overhead.",
    points: [
      "Generous free tier keeps the core plan free",
      "Schema-managed through versioned SQL migrations",
      "Workspace-scoped tables for clients, projects, invoices",
      "Scale-to-zero between traffic peaks",
    ],
  },
  {
    layer: "Identity",
    tech: "Clerk JWT · RBAC",
    description:
      "Authentication with social OAuth, MFA and session revocation — passwords never touch our servers.",
    points: [
      "Bearer JWT verified in FastAPI middleware against Clerk JWKS",
      "Role-based access within each workspace",
      "Workspace-scoped isolation for every query",
      "Seamless session refresh across web, desktop and mobile",
    ],
  },
  {
    layer: "Storage",
    tech: "Cloudinary object storage",
    description:
      "Contract PDFs, receipts and client deliverables served from a global CDN with signed uploads.",
    points: [
      "Signed URL uploads generated by FastAPI",
      "Automated PDF invoice rendering straight to storage",
      "Access-logged, per-client share tokens",
      "Encrypted at rest",
    ],
  },
  {
    layer: "Hardening",
    tech: "Middleware & rate limits",
    description:
      "A hardened request pipeline in front of every endpoint.",
    points: [
      "Per-IP sliding-window rate limits on public endpoints",
      "Strict CORS allow-list and sanitized error responses",
      "Security headers on every response (HSTS, nosniff, DENY)",
      "Tokenized, revocable share links",
    ],
  },
];

const monorepo = [
  { path: "apps/web", desc: "Next.js 16 App Router · Tailwind CSS v4 · shadcn/ui" },
  { path: "apps/api", desc: "FastAPI · Python 3.12 · SQLAlchemy 2.0 · Neon Postgres" },
  { path: "apps/desktop", desc: "Electron shell · global quick capture" },
  { path: "apps/mobile", desc: "React Native · Expo · push + offline sync" },
  { path: "packages/types", desc: "Shared TypeScript contracts for every client" },
];

export default function ArchitecturePage() {
  return (
    <LandingShell>
      <Navbar />

      <main className="flex-1">
        <PageHero
          eyebrow="Architecture"
          title="Free-first,"
          accent="serverless by design."
          desc="Built so the running cost of your workspace stays near zero — Neon Postgres that scales to idle, an async Python core, and no servers to babysit."
        />

        <Section className="border-t-0">
          <Container>
            <div className="border-t border-line">
              {tiers.map((tier, idx) => (
                <Rise key={tier.layer} delay={idx * 0.04}>
                  <div className="grid gap-3 border-b border-line py-8 sm:grid-cols-[240px_1fr] sm:gap-10">
                    <div className="flex items-start gap-3">
                      <span className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-[2px] border border-line bg-fg/[0.03] font-mono text-[10px] text-brand-light">
                        {String(idx + 1).padStart(2, "0")}
                      </span>
                      <div>
                        <div className="mb-1.5 font-mono text-[10px] uppercase tracking-widest text-brand">
                          {tier.layer}
                        </div>
                        <h2 className="font-display text-[16px] font-semibold leading-snug text-fg">
                          {tier.tech}
                        </h2>
                      </div>
                    </div>
                    <div>
                      <p className="mb-4 text-[14px] leading-7 text-muted">{tier.description}</p>
                      <div className="grid gap-x-8 gap-y-2 sm:grid-cols-2">
                        {tier.points.map((p) => (
                          <div key={p} className="flex items-start gap-2.5 text-[13px] leading-5 text-fg/90">
                            <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-muted/50" />
                            <span>{p}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </Rise>
              ))}
            </div>
          </Container>
        </Section>

        <Section>
          <Container>
            <Rise className="max-w-2xl">
              <h2 className="text-3xl font-medium tracking-tight leading-[1.1] text-fg sm:text-4xl lg:text-5xl">
                One repository,
                <br />
                four clients, shared contracts.
              </h2>
              <p className="mt-5 text-base font-light text-muted sm:text-lg">
                Web, API, desktop and mobile live together with a shared types package, so
                every client speaks the same schema.
              </p>
            </Rise>
            <Rise delay={0.08} className="mx-auto mt-12 max-w-3xl">
              <WindowFrame title="freelance-book/">
                <div className="p-4 font-mono text-[12px] leading-6 sm:p-5">
                  {monorepo.map((m) => (
                    <div
                      key={m.path}
                      className="flex flex-col gap-0.5 border-b border-line/60 py-2 last:border-b-0 sm:flex-row sm:items-baseline sm:gap-4"
                    >
                      <span className="shrink-0 text-brand-light">{m.path}</span>
                      <span className="text-muted">{m.desc}</span>
                    </div>
                  ))}
                </div>
              </WindowFrame>
            </Rise>
          </Container>
        </Section>
      </main>

      <Footer />
    </LandingShell>
  );
}
