"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { Navbar } from "@/components/landing/Navbar";
import { Footer } from "@/components/landing/Footer";
import {
  Server,
  Database,
  Key,
  Zap,
  CheckCircle2,
  Layers,
  Terminal,
} from "lucide-react";
import { Spotlight } from "@/components/ui/aceternity/spotlight";
import { Meteors } from "@/components/ui/aceternity/meteors";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export default function ArchitecturePage() {
  const tiers = [
    {
      layer: "Presentation Layer",
      tech: "Next.js 16 + Electron + Expo",
      icon: Layers,
      badge: "Layer 1",
      badgeVariant: "emerald" as const,
      color: "text-emerald-400 bg-emerald-500/10 border-emerald-500/20",
      description: "Unified cross-platform client ecosystem sharing TypeScript types, design tokens, and components.",
      features: [
        "Next.js 16 App Router with Server Components & Tailwind CSS v4",
        "Windows Electron app with Global Hotkey Quick Capture (Ctrl+Shift+F)",
        "Android React Native Expo companion with push notifications",
        "Framer Motion for 60fps micro-animations and smooth page transitions",
      ],
    },
    {
      layer: "Backend Engine",
      tech: "Python 3.12+ FastAPI Async REST",
      icon: Server,
      badge: "Layer 2",
      badgeVariant: "indigo" as const,
      color: "text-indigo-400 bg-indigo-500/10 border-indigo-500/20",
      description: "High-throughput asynchronous Python backend utilizing Pydantic V2 models and automatic OpenAPI documentation.",
      features: [
        "Sub-20ms latency async request handlers",
        "SQLAlchemy 2.0 async engine with connection pooling",
        "Automatic Swagger / OpenAPI 3.1 spec generation at /docs",
        "Built-in AI orchestration for Gemini & OpenAI LLMs",
      ],
    },
    {
      layer: "Primary Database",
      tech: "Cloudflare D1 Serverless SQL",
      icon: Database,
      badge: "Layer 3",
      badgeVariant: "cyan" as const,
      color: "text-cyan-400 bg-cyan-500/10 border-cyan-500/20",
      description: "Global serverless SQLite-compatible database with zero maintenance overhead, automated backups, and instant edge replication.",
      features: [
        "100% Free Core Tier for freelancers with generous storage limits",
        "SQLite dialect managed asynchronously via aiosqlite and SQLAlchemy",
        "Structured schemas for Workspaces, Clients, Projects, Tasks, and Invoices",
        "Zero cold-starts and automatic geo-distributed read replicas",
      ],
    },
    {
      layer: "Identity & Security",
      tech: "Clerk JWT & Role-Based Access Control",
      icon: Key,
      badge: "Layer 4",
      badgeVariant: "default" as const,
      color: "text-purple-400 bg-purple-500/10 border-purple-500/20",
      description: "Enterprise-grade authentication with social OAuth, session revocation, multi-factor authentication, and JWT verification.",
      features: [
        "Encrypted Bearer JWT verification in FastAPI security middleware",
        "Zero password storage on custom servers (SOC-2 Type II compliant)",
        "Workspace-scoped isolation for all multi-tenant queries",
        "Seamless session refresh across Web, Desktop, and Mobile",
      ],
    },
    {
      layer: "Edge Object Storage",
      tech: "Cloudflare R2 Object Storage",
      icon: Shield,
      badge: "Layer 5",
      badgeVariant: "amber" as const,
      color: "text-amber-400 bg-amber-500/10 border-amber-500/20",
      description: "S3-compatible object storage with zero egress fees for invoice PDFs, receipts, and client deliverables.",
      features: [
        "Zero data egress fees on client asset downloads",
        "Pre-signed secure upload URLs generated by FastAPI",
        "Automated PDF invoice generation and direct R2 storage",
        "Encrypted at rest with custom access tokens",
      ],
    },
    {
      layer: "Cache & Workflows",
      tech: "Upstash Redis + Inngest",
      icon: Zap,
      badge: "Layer 6",
      badgeVariant: "destructive" as const,
      color: "text-rose-400 bg-rose-500/10 border-rose-500/20",
      description: "Serverless Redis caching layer and event-driven background job orchestration for reminders and reports.",
      features: [
        "API rate limiting and session token caching",
        "Scheduled invoice payment reminder emails via Brevo",
        "Weekly freelancer profitability report generation",
        "Idempotent event processing with step-by-step retry logic",
      ],
    },
  ];

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col selection:bg-emerald-500 selection:text-slate-950">
      <Navbar />

      <main className="flex-1">
        {/* Hero Section with Aceternity Spotlight */}
        <section className="relative pt-20 pb-16 overflow-hidden border-b border-slate-900 bg-gradient-to-b from-slate-950 via-slate-900/30 to-slate-950">
          <Spotlight className="-top-30 left-10 md:left-1/3" fill="rgba(99, 102, 241, 0.25)" />

          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-10">
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="inline-flex mb-6"
            >
              <Badge variant="indigo" className="px-4 py-1.5 text-xs font-semibold gap-2">
                <Cpu className="w-3.5 h-3.5" /> Production Blueprint Architecture
              </Badge>
            </motion.div>

            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="text-4xl sm:text-6xl font-extrabold text-white tracking-tight leading-tight max-w-4xl mx-auto mb-6"
            >
              Free-First, Edge-Optimized{" "}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 via-teal-300 to-emerald-400">
                System Architecture.
              </span>
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="text-base sm:text-xl text-slate-300 max-w-3xl mx-auto mb-10 leading-relaxed font-normal"
            >
              Designed for zero server maintenance, blazing speed, and $0 baseline hosting costs using Cloudflare D1, FastAPI, and Clerk.
            </motion.p>
          </div>
        </section>

        {/* Architecture Layers Breakdown with shadcn Card */}
        <section className="py-20 bg-slate-950">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {tiers.map((tier, idx) => {
                const Icon = tier.icon;
                return (
                  <motion.div
                    key={idx}
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true, margin: "-100px" }}
                    transition={{ duration: 0.5, delay: idx * 0.08 }}
                    whileHover={{ y: -4 }}
                  >
                    <Card className="h-full p-8 bg-slate-900/50 border-slate-800/80 hover:border-indigo-500/40 transition-all flex flex-col justify-between group shadow-xl">
                      <div>
                        <div className="flex items-center justify-between mb-6">
                          <div className={`w-12 h-12 rounded-2xl border flex items-center justify-center ${tier.color}`}>
                            <Icon className="w-6 h-6" />
                          </div>
                          <Badge variant={tier.badgeVariant} className="text-[11px] font-mono">
                            {tier.badge}
                          </Badge>
                        </div>

                        <div className="text-xs font-semibold text-emerald-400 uppercase tracking-wider mb-1 font-mono">
                          {tier.layer}
                        </div>
                        <h3 className="text-xl font-bold text-white mb-2 group-hover:text-indigo-300 transition-colors">
                          {tier.tech}
                        </h3>
                        <p className="text-sm text-slate-400 leading-relaxed mb-6 font-normal">
                          {tier.description}
                        </p>

                        <div className="space-y-2 pt-4 border-t border-slate-800/80">
                          {tier.features.map((feat, fIdx) => (
                            <div key={fIdx} className="flex items-start gap-2.5 text-xs text-slate-300 font-normal">
                              <CheckCircle2 className="w-3.5 h-3.5 text-indigo-400 flex-shrink-0 mt-0.5" />
                              <span className="leading-snug">{feat}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    </Card>
                  </motion.div>
                );
              })}
            </div>

            {/* Monorepo Topology Box with Aceternity Meteors */}
            <div className="mt-16 p-8 sm:p-12 rounded-3xl bg-slate-900/60 border border-slate-800 backdrop-blur-2xl relative overflow-hidden shadow-2xl">
              <Meteors number={15} />
              <div className="relative z-10">
                <div className="flex items-center gap-3 mb-6">
                  <Terminal className="w-6 h-6 text-emerald-400" />
                  <h3 className="text-2xl font-bold text-white">Monorepo Topology</h3>
                </div>
                <p className="text-sm text-slate-300 mb-6 max-w-2xl font-normal">
                  Structured as a clean, type-safe monorepo separating web frontend, Python REST API, desktop shell, mobile client, and shared UI primitives.
                </p>

                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 font-mono text-xs">
                  <div className="p-4 rounded-2xl bg-slate-950/90 border border-slate-800">
                    <div className="text-emerald-400 font-bold mb-1">apps/web</div>
                    <div className="text-slate-400">Next.js 16 App Router, Tailwind CSS v4, shadcn/ui</div>
                  </div>
                  <div className="p-4 rounded-2xl bg-slate-950/90 border border-slate-800">
                    <div className="text-indigo-400 font-bold mb-1">apps/api</div>
                    <div className="text-slate-400">FastAPI, Python 3.12, SQLAlchemy 2.0, Cloudflare D1</div>
                  </div>
                  <div className="p-4 rounded-2xl bg-slate-950/90 border border-slate-800">
                    <div className="text-purple-400 font-bold mb-1">apps/desktop</div>
                    <div className="text-slate-400">Electron, Windows Global Shortcut (Ctrl+Shift+F)</div>
                  </div>
                  <div className="p-4 rounded-2xl bg-slate-950/90 border border-slate-800">
                    <div className="text-pink-400 font-bold mb-1">apps/mobile</div>
                    <div className="text-slate-400">React Native, Expo, Push Alerts, Offline Sync</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
